plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish'
}

def defVersion = '0.8'
int defVersionCode = 2026083100

group = 'com.github.HChenX'
version = defVersion

android {
    namespace 'com.hchen.hyperislandapi'
    compileSdk 37

    defaultConfig {
        minSdk 29
        targetSdk 37
        // noinspection HighAppVersionCode
        versionCode defVersionCode
        versionName defVersion

        aarMetadata {
            minCompileSdk = 26
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }

    buildFeatures {
        buildConfig false
    }
}

tasks.register('androidSourcesJar', Jar) {
    from android.sourceSets.main.java.srcDirs
}

dependencies {
    implementation libs.appcompat
    implementation libs.jackson.databind
}

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.HChenX'
                artifactId = 'HyperIslandApi'
                version = defVersion

                artifact androidSourcesJar
            }
        }
    }
}